spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/firefox
#    url : jdbc:mysql://mysql-container-new:3306/firefox
    username: root
    password: 2512
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging:
  level:
    com.firewolf.cont : info
    org.hibernate.SQL : debug
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.hibernate.type : trace

#kakao
kakao:
  client_id: b182ecd9e6b3167982c8a6214f6fe9a8
  redirect_uri: http://localhost:8080/mainPage